import os
from datetime import datetime
from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import mm
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, Image
)

def create_pdf_report(pdf_path, case, original_path, heatmap_path=None):
    doc = SimpleDocTemplate(
        pdf_path,
        pagesize=A4,
        rightMargin=16*mm,
        leftMargin=16*mm,
        topMargin=14*mm,
        bottomMargin=14*mm
    )

    styles = getSampleStyleSheet()
    title = ParagraphStyle(
        "TitleCenter", parent=styles["Title"], alignment=TA_CENTER,
        fontSize=20, leading=24, spaceAfter=4
    )
    subtitle = ParagraphStyle(
        "Subtitle", parent=styles["Normal"], alignment=TA_CENTER,
        fontSize=9, textColor=colors.grey, spaceAfter=12
    )
    heading = ParagraphStyle(
        "Heading", parent=styles["Heading2"], fontSize=12,
        textColor=colors.HexColor("#17324D"), spaceBefore=8, spaceAfter=6
    )
    normal = ParagraphStyle(
        "Normal2", parent=styles["BodyText"], fontSize=9.5, leading=14
    )

    story = []
    story.append(Paragraph("PATHOVISION AI", title))
    story.append(Paragraph(
        "AI-Assisted Histopathology Analysis Report", subtitle
    ))

    info = [
        ["Case Reference", str(case.get("case_ref") or "-")],
        ["Patient/Reference ID", str(case.get("patient_ref") or "-")],
        ["Specimen", str(case.get("specimen") or "-")],
        ["Pathologist", str(case.get("pathologist") or "-")],
        ["Medical ID", str(case.get("medical_id") or "-")],
        ["Institution", str(case.get("institution") or "-")],
        ["Analysis Date", str(case.get("created_at") or datetime.now().isoformat())],
    ]

    table = Table(info, colWidths=[48*mm, 125*mm])
    table.setStyle(TableStyle([
        ("BACKGROUND", (0,0), (0,-1), colors.HexColor("#EAF2F7")),
        ("GRID", (0,0), (-1,-1), 0.4, colors.HexColor("#C7D4DE")),
        ("FONTNAME", (0,0), (0,-1), "Helvetica-Bold"),
        ("FONTSIZE", (0,0), (-1,-1), 9),
        ("VALIGN", (0,0), (-1,-1), "TOP"),
        ("LEFTPADDING", (0,0), (-1,-1), 7),
        ("RIGHTPADDING", (0,0), (-1,-1), 7),
        ("TOPPADDING", (0,0), (-1,-1), 6),
        ("BOTTOMPADDING", (0,0), (-1,-1), 6),
    ]))
    story += [table, Spacer(1, 10)]

    story.append(Paragraph("AI RESULT", heading))
    result_table = Table([
        ["Prediction", str(case["prediction"])],
        ["Confidence", f'{float(case["confidence"]):.2f}%'],
        ["Model", "ResNet50 / PCam classifier"],
    ], colWidths=[48*mm, 125*mm])
    result_table.setStyle(TableStyle([
        ("GRID", (0,0), (-1,-1), 0.4, colors.HexColor("#C7D4DE")),
        ("FONTNAME", (0,0), (0,-1), "Helvetica-Bold"),
        ("FONTSIZE", (0,0), (-1,-1), 10),
        ("BACKGROUND", (0,0), (0,-1), colors.HexColor("#F4F7F9")),
        ("TOPPADDING", (0,0), (-1,-1), 7),
        ("BOTTOMPADDING", (0,0), (-1,-1), 7),
    ]))
    story += [result_table, Spacer(1, 8)]

    story.append(Paragraph("ORIGINAL HISTOPATHOLOGY IMAGE", heading))
    if os.path.exists(original_path):
        img = Image(original_path)
        img._restrictSize(150*mm, 80*mm)
        story.append(img)

    if heatmap_path and os.path.exists(heatmap_path):
        story.append(Paragraph("GRAD-CAM EXPLAINABILITY HEATMAP", heading))
        heat = Image(heatmap_path)
        heat._restrictSize(150*mm, 80*mm)
        story.append(heat)

    story.append(Spacer(1, 8))
    story.append(Paragraph(
        "<b>Interpretation:</b> The prediction and heatmap are generated by "
        "the trained AI model. The heatmap is intended to visualize image "
        "regions contributing to the model output.", normal
    ))
    story.append(Spacer(1, 6))
    story.append(Paragraph(
        "<b>IMPORTANT DISCLAIMER:</b> This application is an AI-assisted "
        "research and decision-support prototype. It is not a replacement "
        "for professional pathological diagnosis and should not be used "
        "as the sole basis for clinical decisions.", normal
    ))

    doc.build(story)
